### ISSUE TITLE
getAccountBalances($args)

### ISSUE THREAD

**Issue by senhanxiao** [Codaone/bitshares-php#1]
How do I pass this parameter!!

**Comment by juhanihaapala** [comment]
Example code to get nathan bts balance:

```
<?php
use \Codaone\BitShares\BitShares;
require 'vendor/autoload.php';

$bitshares = new BitShares();
$nathanBtsBalance = $bitshares->getAccountBalances('1.2.298', ['1.3.0']);
```

Those api call parameters can be found on documentation for example here:
https://dev.bitshares.works/en/master/api/blockchain_api/database.html#get-account-balances
